name: Knowledge Base Hourly Keepalive
on:
  schedule:
    - cron: "0 * * * *" # every hour (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update timestamp in KnowledgeBase.md
        shell: bash
        run: |
          set -euo pipefail
          FILE="KnowledgeBase.md"
          TS="$(date -u +"%Y-%m-%d %H:%M:%S UTC")"
          MARK_START="<!-- AUTO-UPDATE-TIMESTAMP -->"
          MARK_LINE="$MARK_START Last auto check: $TS"
          if grep -q "$MARK_START" "$FILE"; then
            sed -i "s|^<!-- AUTO-UPDATE-TIMESTAMP -->.*$|$MARK_LINE|" "$FILE"
          else
            awk -v ins="$MARK_LINE" 'NR==1 {print; print ins; next} {print}' "$FILE" > "$FILE.tmp" && mv "$FILE.tmp" "$FILE"
          fi
      - name: Commit changes (if any)
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add KnowledgeBase.md
            git commit -m "chore(kb): hourly keepalive timestamp update"
            git push
          else
            echo "No changes to commit."
          fi
